# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: CI/CD

on:
  workflow_call:
    inputs:
      test-enabled:
        required: false
        type: boolean
        default: true
        description: 'Should run tests?'
      test-architecture:
        required: false
        type: string
        default: 'amd64'
        description: 'Architecture to use for running tests'
      test-distribution:
        required: false
        type: string
        default: 'bookworm'
        description: 'Distribution to use for running tests'
      test-timeout:
        required: false
        type: number
        default: 10
        description: 'Test timeout in seconds'
      coverage-enabled:
        required: false
        type: boolean
        default: true
        description: 'Should run with coverage?'
      coverage-threshold:
        required: false
        type: number
        default: 80
        description: 'Minimum coverage threshold'
      package-architecture:
        required: false
        type: string
        default: '["armhf", "arm64", "amd64"]'
        description: 'Architecture to run builds on (must be valid JSON array format)'
      package-distribution:
        required: false
        type: string
        default: '["bullseye", "bookworm"]'
        description: 'Distribution to run builds on (must be valid JSON array format)'
      package-type:
        required: false
        type: string
        default: 'wheel, fpm-deb'
        description: 'Packaging types'
    secrets:
      access-token:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.access-token || github.token }}
  GITHUB_ACTION: "TRUE"

jobs:
  test:
    name: Run tests
    if: ${{ inputs.test-enabled }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Build and test
        uses: devcontainers/ci@v0.3
        with:
          subFolder: "${{ github.workspace }}"
          configFile: .devcontainer/${{ inputs.test-architecture }}-${{ inputs.test-distribution }}-container/devcontainer.json
          push: never
          runCmd: |
            python3 -m venv /tmp/venv && source /tmp/venv/bin/activate
            pip install mypy flake8 pytest pytest-timeout
            pip install .
            
            mypy --install-types --non-interactive || true
            mypy || { echo "mypy exited with $?"; exit 1; }
            flake8 || { echo "flake exited with $?"; exit 1; }
            
            if [ ${{ inputs.coverage-enabled }} == true ]; then
              pip install coverage
              coverage run -m pytest --timeout=${{ inputs.test-timeout }} || { echo "pytest exited with $?"; exit 1; }
              coverage report --show-missing --fail-under=${{ inputs.coverage-threshold }} || { echo "coverage exited with $?"; exit 1; }
            else
              pytest --timeout=${{ inputs.test-timeout }} || { echo "pytest exited with $?"; exit 1; }
            fi

      - name: Coverage comment
        if: ${{ inputs.coverage-enabled && github.event_name == 'pull_request' }}
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

  prepare:
    name: Prepare release
    if: always()
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Extract version
        id: set-version
        run: |
          VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ "${GITHUB_REF#refs/tags/v}" =~ $VERSION_REGEX ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            VERSION=$(grep -oP "version=['\"]\K[^\"]+(?=['\"])" setup.py)
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          fi

  build_wheel:
    name: Create wheel package
    if: always() && contains(inputs.package-type, 'wheel')
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Update version in setup.py
        run: |
          if [ -f setup.py ]; then
            sed -i "s/version=['\"].*['\"]/version='${{ needs.prepare.outputs.version }}'/" setup.py
          else
            echo "setup.py not found"
            exit 1
          fi

      - name: Create package
        uses: devcontainers/ci@v0.3
        with:
          subFolder: "${{ github.workspace }}"
          configFile: .devcontainer/amd64-bookworm-container/devcontainer.json
          push: never
          runCmd: pack_python . -s wheel || { echo "pack_python exited with $?"; exit 1; }

      - name: Upload package
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_wheel
          path: dist/*.whl
          if-no-files-found: error

  build_fpm-deb:
    name: Create debian package with FPM
    if: always() && contains(inputs.package-type, 'fpm-deb')
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ${{ fromJson(inputs.package-distribution) }}
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Update version in setup.py
        run: |
          if [ -f setup.py ]; then
            sed -i "s/version=['\"].*['\"]/version='${{ needs.prepare.outputs.version }}'/" setup.py
          else
            echo "setup.py not found"
            exit 1
          fi

      - name: Create package
        uses: devcontainers/ci@v0.3
        with:
          subFolder: "${{ github.workspace }}"
          configFile: .devcontainer/amd64-${{ matrix.distribution }}-container/devcontainer.json
          push: never
          runCmd: |
            pack_python . -s fpm-deb || { echo "pack_python exited with $?"; exit 1; }
            
            DISTRIBUTION="$(echo ${{ matrix.distribution }} | cut -d'-' -f2)"
            
            for package in $(find dist -name *.deb)
            do
              mv -vf $package $(dirname $package)/${DISTRIBUTION}_$(basename $package)
            done

      - name: Upload package
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_fpm-deb_${{ matrix.distribution }}
          path: dist/*.deb
          if-no-files-found: error

  build_dh-virtualenv:
    name: Create debian package with dh-virtualenv
    if: always() && contains(inputs.package-type, 'dh-virtualenv')
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ${{ fromJson(inputs.package-architecture) }}
        distribution: ${{ fromJson(inputs.package-distribution) }}
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Update version in setup.py
        run: |
          if [ -f setup.py ]; then
            sed -i "s/version=['\"].*['\"]/version='${{ needs.prepare.outputs.version }}'/" setup.py
          else
            echo "setup.py not found"
            exit 1
          fi

      - name: Create package
        uses: devcontainers/ci@v0.3
        with:
          subFolder: "${{ github.workspace }}"
          configFile: .devcontainer/${{ matrix.architecture }}-${{ matrix.distribution }}-container/devcontainer.json
          push: never
          runCmd: |
            WORKSPACE="/workspaces/$(basename ${{ github.workspace }})"
            BUILDROOT="/var/chroot/buildroot"
            
            rsync -av --exclude ".git" --mkpath "$WORKSPACE/" "$BUILDROOT$WORKSPACE/"
            
            schroot -p -c buildroot -- apt update && apt install -y python3-stdeb packaging-tools
            schroot -p -c buildroot -- pack_python . -s dh-virtualenv || { echo "pack_python exited with $?"; exit 1; }
            
            rsync -av --include "*_*.deb" --exclude "*" --mkpath "$BUILDROOT$WORKSPACE/dist/" "$WORKSPACE/dist/"
            
            DISTRIBUTION="$(echo ${{ matrix.distribution }} | cut -d'-' -f2)"
            
            for package in $(find dist -name *.deb)
            do
              mv -vf $package $(dirname $package)/${DISTRIBUTION}_$(basename $package)
            done

      - name: Upload package
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_dh-virtualenv_${{ matrix.architecture }}_${{ matrix.distribution }}
          path: dist/*.deb
          if-no-files-found: error

  release:
    name: Create release
    if: always() && startsWith(github.ref, 'refs/tags/')
    needs: [ prepare, build_wheel, build_fpm-deb, build_dh-virtualenv ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Update version in setup.py
        run: |
          if [ -f setup.py ]; then
            sed -i "s/version=['\"].*['\"]/version='${{ needs.prepare.outputs.version }}'/" setup.py
          else
            echo "setup.py not found"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -am "Update version to ${{ needs.prepare.outputs.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Create release
        uses: EffectiveRange/version-release-github-action@v2
